name: Testing Stuff

on:
  push:
    branches:
      - main

env:
  CONDITION: ${{github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        id: commit_messages
        if: false
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: print condition
        run: echo $CONDITION

      - uses: sarisia/actions-status-discord@v1
        if: ${{steps.commit_messages.outcome == "success"}}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: 'Deploy'
          description: 'A new version of Pokedex deployed!'
          username: Pokedex

      # - name: Test Success
      #   uses: rjstone/discord-webhook-notify@v2
      #   # if: ${{steps.deploy.outcome == "success"}}
      #   if: success()
      #   with:
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      #     severity: info
      #     details: A new version of Pokedex deployed!
